# Generated by Django 6.0.2 on 2026-02-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('metric', models.CharField(choices=[('latency_p95', 'Latency p95'), ('error_rate', 'Error rate'), ('throughput', 'Throughput')], max_length=20)),
                ('threshold', models.FloatField()),
                ('comparison', models.CharField(choices=[('>', '>'), ('<', '<')], max_length=5)),
                ('severity', models.CharField(choices=[('info', 'info'), ('warn', 'warn'), ('critical', 'critical')], max_length=10)),
                ('cooldown_minutes', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField()),
                ('value', models.FloatField()),
                ('resolved', models.BooleanField(default=False)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alertpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('bucket_start', models.DateTimeField()),
                ('bucket_size', models.CharField(choices=[('1m', '1 minute'), ('5m', '5 minutes'), ('1h', '1 hour')], max_length=10)),
                ('request_count', models.IntegerField()),
                ('error_count', models.IntegerField()),
                ('p95_latency_ms', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'bucket_start'], name='core_aggreg_project_3c0c44_idx')],
                'unique_together': {('project', 'endpoint', 'bucket_start', 'bucket_size')},
            },
        ),
        migrations.CreateModel(
            name='RequestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('latency_ms', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'timestamp'], name='core_reques_project_345abc_idx'), models.Index(fields=['status_code'], name='core_reques_status__1fc08d_idx'), models.Index(fields=['endpoint'], name='core_reques_endpoin_a11dca_idx')],
            },
        ),
    ]
